config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { registrations: "registrations" }
  root "pages#show", page: "home"

  resources :pages, only: [:index, :show]

  resources :fridges
  resources :users
  resources :fridgecategories, except: [:index, :show] do
    member do
      post 'initial'
      get 'initial'
    end
  end
  resources :groceries, except: [:show] do
    member do
      get 'accept'
      post 'accept'
    end
  end
  resources :grocerylists
  resources :recipes do
    member do
      post 'index'
    end
  end

  post 'groceries/email' => 'groceries#email', as: :email

end

app/models/grocerylist.rb
class Grocerylist < ActiveRecord::Base
  belongs_to :user
  has_many :groceries

  validates :name, presence: true
end

app/controllers/grocerylists_controller.rb
class GrocerylistsController < ApplicationController
  def show
    @user = current_user
    @grocerylist = @user.grocerylist
    @groceries = @grocerylist.groceries
    @fridgecategories = @user.fridgecategories.order(name: :asc)
    @grocery = Grocery.new
  end

  def new
    if user_signed_in?
      @grocerylist = Grocerylist.new
    else
      flash[:notice] = "Please sign in"
      redirect_to new_user_session_path
    end
  end

  def create
    @grocerylist = Grocerylist.new(grocerylist_params)
    @grocerylist.user = current_user

    if @grocerylist.save
      flash[:notice] = "Grocery list created successfully"
      redirect_to new_fridgecategory_path
    else
      flash[:notice] = @grocerylist.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def edit
    @grocerylist = Grocerylist.find(params[:id])
    if current_user != @grocerylist.user
      flash[:notice] = 'You cannot edit this grocery list'
      redirect_to @grocerylist
    end
  end


  def update
    @grocerylist = Grocerylist.find(params[:id])
    if @grocerylist.update_attributes(grocerylist_params)
      flash[:notice] = "Grocery List edited successfully"
      redirect_to @grocerylist
    else
      flash[:notice] = @grocerylist.errors.full_messages.join(', ')
      render 'edit'
    end
  end

  private

  def grocerylist_params
    params.require(:grocerylist).permit(:name)
  end
end

app/views/grocerylists/_form.html.erb
<%= form_for @grocerylist do |f| %>
  <%= f.text_area :name, placeholder: "Name"%>
  <%= f.submit "Save Grocery List" %>
<% end %>

app/views/grocerylists/edit.html.erb
<%= render "form" %>

app/views/grocerylists/new.html.erb
<div class="sign-up">
  <h2>Name Your Grocery List</h2>
  <p>
    You'll be able to keep groceries in your grocery list and add them to your fridge later on by pressing the "accept" button.
  </p>
  <%= render "form" %>
</div>

app/views/grocerylists/show.html.erb
<div class="fridge-page">
  <div class="list">
    <h1><%= link_to @grocerylist.name, edit_grocerylist_path(@grocerylist) %></h1>

    <table>
      <% @groceries.each do |g| %>
      <tr>
        <td>
          <%= link_to g.name, edit_grocery_path(g) %>
        </td>
        <td>
          <div class="accept-button">
            <%= link_to '', accept_grocery_path(g), class: 'fa fa-check' %>
          </div>
        </td>
        <td>
          <div class="delete-button">
            <%= link_to '', g, method: :delete, data: { confirm: 'You sure?' }, class: 'fa fa-times' %>
          </div>
        </td>
      </tr>
      <% end %>
    </table>
  </div>

  <div class="add-things">
    <h2>Add a Grocery:</h2>
    <div class="new-grocery">
      <%= form_for @grocery do |f| %>
        <%= f.text_area :name, placeholder: 'Enter a name' %>
        <%= f.text_area :quantity, placeholder: 'Enter an amount' %>
        <%= f.label :fridgecategory_id, "Category:" %>
        <%= f.collection_radio_buttons(:fridgecategory_id, @fridgecategories, :id, :name) %>
        <%= f.submit "Save Grocery" %>
      <% end %>

    </div>
  </div>
</div>