config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { registrations: "registrations" }
  root "pages#show", page: "home"

  resources :pages, only: [:index, :show]

  resources :fridges
  resources :users
  resources :fridgecategories, except: [:index, :show] do
    member do
      post 'initial'
      get 'initial'
    end
  end
  resources :groceries, except: [:show] do
    member do
      get 'accept'
      post 'accept'
    end
  end
  resources :grocerylists
  resources :recipes do
    member do
      post 'index'
    end
  end

  post 'groceries/email' => 'groceries#email', as: :email

end

app/models/fridge.rb
class Fridge < ActiveRecord::Base
  belongs_to :user
  has_many :fridgecategories, dependent: :destroy
  has_many :groceries, through: :fridgecategories

  validates :name, presence: true
  validates :user_id, presence: true
  validates :user_id, numericality: { only_integer: true }
end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController
  def index
    @user = current_user
    @fridge = @user.fridge
    @grocerylist = @user.grocerylist
  end

  def show
    @user = current_user
    @fridge = @user.fridge
    @fridgecategories = @fridge.fridgecategories.order(name: :asc)
    @fridgecategory = Fridgecategory.new
    @grocery = Grocery.new
  end

  def new
    if user_signed_in?
      @fridge = Fridge.new
    else
      flash[:notice] = "Please sign in"
      redirect_to new_user_session_path
    end
  end

  def create
    @fridge = Fridge.new(fridge_params)
    @fridge.user = current_user

    if @fridge.save
      flash[:notice] = "Fridge created successfully"
      redirect_to new_grocerylist_path
    else
      flash[:notice] = @fridge.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def edit
    @fridge = Fridge.find(params[:id])
    if current_user != @fridge.user
      flash[:notice] = 'You cannot edit this fridge'
      redirect_to fridge_path(@fridge)
    end
  end


  def update
    @fridge = Fridge.find(params[:id])

    if @fridge.update_attributes(fridge_params)
      flash[:notice] = "Fridge edited successfully"
      redirect_to fridge_path(@fridge)
    else
      flash[:notice] = @fridge.errors.full_messages.join(', ')
      render 'edit'
    end
  end

  private

  def fridge_params
    params.require(:fridge).permit(:name)
  end
end

app/views/fridges/_form.html.erb
<%= form_for @fridge do |f| %>
  <%= f.text_area :name, placeholder: "Name"%>
  <%= f.submit "Save Fridge" %>
<% end %>

app/views/fridges/edit.html.erb
<%= render "form" %>

app/views/fridges/index.html.erb
<div class="fridges-index">
  <h1 id = "fridge"><%= link_to 'My Fridge', fridge_path(@fridge) unless @fridge.blank? %></h1>
  <h1 id = "grocerylist"><%= link_to 'Grocery List', grocerylist_path(@grocerylist) unless @grocerylist.blank? %></h1>
  <h1 id = "recipes"><%= link_to 'Recipes', groceries_path %></h1>
</div>

app/views/fridges/new.html.erb
<div class="sign-up">
  <h2>Now...Give Your Fridge a Name!</h2>
  <p>
    This can either be something simple like "Fridge", or more customized like "Jane's Fridge."
  </p>

  <%= render "form" %>
</div>

app/views/fridges/show.html.erb
<div class="fridge-page">
  <div class="list">
    <p>
      <h1><%= link_to @fridge.name, edit_fridge_path(@fridge) %></h1>
    </p>

    <table>
      <thead>
        <% @fridgecategories.each do |fc| %>
        <tr>
          <td> </td>
          <th>
            <h3 class = "delete-fc"><%= link_to fc.name, edit_fridgecategory_path(fc) %></h3>
          </th>
          <td class = "delete-category">
            <%= link_to '', fc, method: :delete, data: { confirm: 'You sure?' }, class: 'fa fa-times' %>
          </td>
        </tr>
        <tr>
          <% @groceries = fc.groceries.order(name: :asc) %>
          <% @groceries.each do |grocery| %>
            <% if grocery.grocerylist_id == nil %>

              <% if !grocery.exp_date.nil? && grocery.exp_date <= 2.day.from_now && grocery.exp_date > 0.day.from_now %>
              <td> </td>
              <td id = "almost-expired">
                <%= link_to grocery.name, edit_grocery_path(grocery) %> - Almost Expired
              </td>
              <td class = "delete-grocery">
                <%= link_to '', grocery, method: :delete, data: { confirm: 'You sure?' }, class: 'fa fa-times' %>
              </td>

                <% elsif !grocery.exp_date.nil? && grocery.exp_date <= Date.current %>
                <td> </td>
                <td id = "expired">
                  <%= link_to grocery.name, edit_grocery_path(grocery) %> - Expired
                </td>
                <td class = "delete-grocery">
                  <%= link_to '', grocery, method: :delete, data: { confirm: 'You sure?' }, class: 'fa fa-times' %>
                </td>

                <% else %>
                <td> </td>
                <td id = "not-expired">
                  <%= link_to grocery.name, edit_grocery_path(grocery) %>
                </td>
                <td class = "delete-grocery">
                  <%= link_to '', grocery, method: :delete, data: { confirm: 'You sure?' }, class: 'fa fa-times' %>
                </td>
                <% end %>
                
             <% end %>
          </tr>
          <% end %>
        <% end %>
      </thead>
    </table>
  </div>
  <div class="add-things">
    <div class="add-category">
      <h2>Add a Category:</h2>
      <%= render "fridgecategories/form" %>
    </div>

    <h2>Add a Grocery:</h2>
    <div class="new-grocery">
      <%= render "/groceries/form" %>
    </div>
  </div>
</div>