config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { registrations: "registrations" }
  root "pages#show", page: "home"

  resources :pages, only: [:index, :show]

  resources :fridges
  resources :users
  resources :fridgecategories, except: [:index, :show] do
    member do
      post 'initial'
      get 'initial'
    end
  end
  resources :groceries, except: [:show] do
    member do
      get 'accept'
      post 'accept'
    end
  end
  resources :grocerylists
  resources :recipes do
    member do
      post 'index'
    end
  end

  post 'groceries/email' => 'groceries#email', as: :email

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = "en">
<head>
  <title>FridgeButler</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Eczar" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.3/foundation.min.css" rel="stylesheet">
  <link href="foundation-overrides.css" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
</head>
<body>
  <nav class="top-bar" data-topbar role="navigation">
    <%= link_to root_path do %>
      <div class="title-area small-6 columns">
          <i class="fa fa-cutlery" aria-hidden="true"></i>
          <span class="fridge">fridge</span><span class="butler">BUTLER</span>
      </div>
    <% end %>
      <section class = "right small-6 columns">
        <% if user_signed_in? %>
          <span class = "option"><%= link_to "LOG OFF", destroy_user_session_path, method: :delete %></span>
          <span class = "option"><%= link_to 'MY ACCOUNT', user_path(current_user) %></span>
          <span class = "option"> <%= link_to 'LEARN MORE', pages_path %> </span>
        <% else %>
          <span class = "option"><%= link_to "SIGN UP", new_user_registration_path %></span>
          <span class = "option"><%= link_to "LOG IN", new_user_session_path %></span>
          <span class = "option"> <%= link_to 'LEARN MORE', pages_path %> </span>
        <% end %>
      </section>
  </nav>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <div class="alert-or-notice">
    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>
  </div>

<%= yield %>

</body>
</html>